language: java

jdk:
  - oraclejdk8

after_success:
  - gradle jacocoTestReport coveralls

branches:
  except:
    - gh-pages

notifications:
  email: false
  
script: ./gradlew clean test

cache:
  directories:
    - $HOME/.gradle
